### ISSUE TITLE
Wallaby.js throws an error in the debug console

### ISSUE THREAD

**Issue by pavsaund** [dolittle-interaction/JavaScript.Build.Aurelia#9]
When running wallabyjs the debug console is filled with an error message that steals a lot of focus, and pushes any actual errors from running the tests down. The runner is still active and works.

Removing the `new AureliaPlugin()` from [`wallaby.js`](https://github.com/dolittle-interaction/JavaScript.Build.Aurelia/blob/master/wallaby.js) seems to remove this, and it still works but I don't know the consequences.

Reproduce: 
1. Open a project with dependency to Javascript.Build.Aurelia.
2. Start Wallaby.js
3. Open the Output window for Wallaby.js Tests in VSCode
4. See an error that looks like this:
````shell
1 failing test, 14 passing​​​​​
​​​​​​​​​​
​​Module not found: Error: Can't resolve 'main' in '/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/aurelia-webpack-plugin/runtime'ModuleNotFoundError: Module not found: Error: Can't resolve 'main' in '/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/aurelia-webpack-plugin/runtime'​​
​​    at factory.create (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/webpack/lib/Compilation.js:814:10)​​
​​    at factory (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/webpack/lib/NormalModuleFactory.js:397:22)​​
​​    at resolver (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/webpack/lib/NormalModuleFactory.js:130:21)​​
​​    at asyncLib.parallel (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/webpack/lib/NormalModuleFactory.js:224:22)​​
​​    at /Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/neo-async/async.js:2825:7​​
​​    at /Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/neo-async/async.js:6886:13​​
​​    at normalResolver.resolve (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/webpack/lib/NormalModuleFactory.js:214:25)​​
​​    at doResolve (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/Resolver.js:184:12)​​
​​    at hook.callAsync (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/Resolver.js:238:5)​​
​​    at _fn1 (eval at create (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)​​
​​    at resolver.getHook.tapAsync (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/aurelia-webpack-plugin/dist/SubFolderPlugin.js:21:17)​​
​​    at _fn0 (eval at create (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:16:1)​​
​​    at resolver.doResolve (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)​​
​​    at hook.callAsync (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/Resolver.js:238:5)​​
​​    at _fn0 (eval at create (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)​​
​​    at hook.callAsync (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/Resolver.js:238:5)​​
​​    at _fn0 (eval at create (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)​​
​​    at resolver.doResolve (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)​​
​​    at hook.callAsync (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/Resolver.js:238:5)​​
​​    at _fn42 (eval at create (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:390:1)​​
​​    at resolver.doResolve (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:37)​​
​​    at hook.callAsync (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/Resolver.js:238:5)​​
​​    at _fn0 (eval at create (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)​​
​​    at hook.callAsync (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/Resolver.js:238:5)​​
​​    at _fn2 (eval at create (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:33:1)​​
​​    at hook.callAsync (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/Resolver.js:238:5)​​
​​    at _fn1 (eval at create (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)​​
​​    at resolver.getHook.tapAsync (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/aurelia-webpack-plugin/dist/SubFolderPlugin.js:21:17)​​
​​    at _fn0 (eval at create (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:16:1)​​
​​    at resolver.doResolve (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)​​
​​    at hook.callAsync (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/Resolver.js:238:5)​​
​​    at _fn0 (eval at create (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)​​
​​    at hook.callAsync (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/Resolver.js:238:5)​​
​​    at _fn0 (eval at create (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)​​
​​    at resolver.doResolve (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)​​
​​    at hook.callAsync (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/Resolver.js:238:5)​​
​​    at _fn43 (eval at create (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:402:1)​​
​​    at hook.callAsync (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/Resolver.js:238:5)​​
​​    at _fn0 (eval at create (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)​​
​​    at resolver.doResolve (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)​​
​​    at hook.callAsync (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/Resolver.js:238:5)​​
​​    at _fn1 (eval at create (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)​​
​​    at hook.callAsync (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/Resolver.js:238:5)​​
​​    at _fn0 (eval at create (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)​​
​​    at fs.stat (/Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:22:13)​​
​​    at /Users/pavneet/code/Dolittle/CustomerProjects/Waterproof/Source/portal/web/node_modules/graceful-fs/polyfills.js:284:29​​
​​    at FSReqWrap.oncomplete (fs.js:170:21)​​
  
  ​​​​when building facets for product for Boiler Water Products creates facet for Boiler Water Products​​​​ ​​​[9 ms]​​​​
    ​​​​
    ​​Error: Invalid Chai property: defined. Did you mean "undefined"?​​
      at Object.proxyGetter [as get] ​node_modules/chai/chai.js:9224​
      at t.<anonymous> ​features/overview/vessels/for_index/when_building_facets_for_consumed_products.js:17:6​

````

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1115619674177327)

**Comment by einari** [comment]
Closing this as we now have a new Wallaby configuration for all this that runs in Node context
